from rapidfuzz import process, fuzz

COMMON_MF_NAME_TO_NSE = {
    "Reliance Industr": "RELIANCE.NS",
    "Reliance Industries": "RELIANCE.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "HDFC Bank Ltd": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Infosys": "INFY.NS",
    "Infosys Ltd": "INFY.NS",
    "TCS": "TCS.NS",
    "Tata Consultancy": "TCS.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "Kotak Mahindra": "KOTAKBANK.NS",
    "Axis Bank": "AXISBANK.NS",
    "SBI": "SBIN.NS",
    "State Bank": "SBIN.NS",
    "Wipro": "WIPRO.NS",
    "HCL Technologies": "HCLTECH.NS",
    "HCL Tech": "HCLTECH.NS",
    "Adani Enterp.": "ADANIENT.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Power": "ADANIPOWER.NS",
    "Adani Green": "ADANIGREEN.NS",
    "RBL Bank": "RBLBANK.NS",
    "Jio Financial": "JIOFIN.NS",
    "Sun TV Network": "SUNTV.NS",
    "HFCL": "HFCL.NS",
    "Welspun Corp": "WELCORP.NS",
    "Minda Corp": "MINDACORP.NS",
    "Sai Life": "SAILIFE.NS",
    "Krishna Institu.": "KIMS.NS",
    "Amber Enterp.": "AMBER.NS",
    "Chola Financial": "CHOLAFIN.NS",
    "Aditya Infotech": "ADITYAINF.NS",
    "Multi Comm. Exc.": "MCX.NS",
    "Eternal": "ETERNAL.NS",
    "Kirloskar Oil": "KIRLOSENG.NS",
    "Craftsman Auto": "CRAFTSMAN.NS",
    "Brigade Enterpr.": "BRIGADE.NS",
    "PNB Housing": "PNBHOUSING.NS",
    "Apar Inds.": "APARINDS.NS",
    "Prestige Estates": "PRESTIGE.NS",
    "Paradeep Phosph.": "PARADEEP.NS",
    "A B Real Estate": "ABREL.NS",
    "Carborundum Uni.": "CARBORUNIV.NS",
    "Deepak Nitrite": "DEEPAKNTR.NS",
    "Balrampur Chini": "BALRAMCHIN.NS",
    "Afcons Infrastr.": "AFCONS.NS",
    "Grindwell Norton": "GRINDWELL.NS",
    "Cams Services": "CAMS.NS",
    "Ellen.Indl.Gas": "ELLEN.NS",
    "Aegis Logistics": "AEGISLOG.NS",
    "Anand Rathi Wea.": "ANANDRATHI.NS",
    "Aster DM Health.": "ASTERDM.NS",
    "Bikaji Foods": "BIKAJI.NS",
    "Capri Global": "CGCL.NS",
    "Usha Martin": "USHAMART.NS",
    "NBCC": "NBCC.NS",
    "NCC": "NCC.NS",
    "IRB Infra.Devl.": "IRB.NS",
    "Manappuram Fin.": "MANAPPURAM.NS",
    "Piramal Finance.": "PIRAMALFIN.NS",
    "EID Parry": "EIDPARRY.NS",
    "Just Dial": "JUSTDIAL.NS",
    "Zydus Wellness": "ZYDUSWELL.NS",
    "Pfizer": "PFIZER.NS",
    "Bayer Crop Sci.": "BAYERCROP.NS",
    "EPL Ltd": "EPL.NS",
    "Karnataka Bank": "KTKBANK.NS",
    "Welspun Living": "WELSPUNLIV.NS",
    "Arvind Ltd": "ARVIND.NS",
    "Marathon Nextgen": "MARATHON.NS",
    "Keystone Realtor": "RUSTOMJEE.NS",
    "Black Box": "BBOX.NS",
    "TVS Srichakra": "TVSSRICHAK.NS",
    "Delhivery": "DELHIVERY.NS",
    "Himadri Special": "HSCL.NS",
    "K P R Mill Ltd": "KPRMILL.NS",
    "Bata India": "BATAINDIA.NS",
    "Castrol India": "CASTROLIND.NS",
    "Triveni Turbine": "TRITURBINE.NS",
    "G S F C": "GSFC.NS",
    "Praj Industries": "PRAJIND.NS",
    "GSFC": "GSFC.NS",
    "Newgen Software": "NEWGEN.NS",
    "Intellect Design": "INTELLECT.NS",
    "Man Infra": "MANINFRA.NS",
    "Lloyds Metals": "LLOYDMETAL.NS",
    "Larsen & Toubro": "LT.NS",
    "M&M": "M&M.NS",
    "Mahindra & Mahin": "M&M.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "ITC": "ITC.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "Titan Company": "TITAN.NS",
    "Sun Pharma": "SUNPHARMA.NS",
    "Ultratech Cem.": "ULTRACEMCO.NS",
    "Tata Steel": "TATASTEEL.NS",
    "NTPC": "NTPC.NS",
    "ONGC": "ONGC.NS",
    "Power Grid Corp": "POWERGRID.NS",
    "Hindalco": "HINDALCO.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Grasim Ind.": "GRASIM.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Coal India": "COALINDIA.NS",
    "Britannia Inds.": "BRITANNIA.NS",
    "Dr Reddy's Labs": "DRREDDY.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "BPCL": "BPCL.NS",
    "Divi's Lab": "DIVISLAB.NS",
    "UPL": "UPL.NS",
    "Cipla": "CIPLA.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Tech Mahindra": "TECHM.NS",
    "Hindustan Unilev": "HINDUNILVR.NS",
    "Nestle India": "NESTLEIND.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "LTIMindtree": "LTIM.NS",
    "Shriram Finance": "SHRIRAMFIN.NS",
    "Trent": "TRENT.NS",
    "Bharat Electron": "BEL.NS",
    "Hindustan Aeron": "HAL.NS",
    "Siemens": "SIEMENS.NS",
    "DLF": "DLF.NS",
    "ABB India": "ABB.NS",
    "Interglobe Avi.": "INDIGO.NS",
    "Varun Beverages": "VBL.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Punjab Natl Bank": "PNB.NS",
    "GAIL": "GAIL.NS",
    "TVS Motor Co.": "TVSMOTOR.NS",
    "Zomato": "ZOMATO.NS",
    "Canara Bank": "CANBK.NS",
    "Cholamandalam": "CHOLAFIN.NS",
    "Godrej Consumer": "GODREJCP.NS",
    "Ambuja Cements": "AMBUJACEM.NS",
    "Yes Bank": "YESBANK.NS",
    "Union Bank": "UNIONBANK.NS",
    "IDFC First Bank": "IDFCFIRSTB.NS",
    "Cummins India": "CUMMINSIND.NS",
    "Persistent Sys": "PERSISTENT.NS",
    "Lupin": "LUPIN.NS",
    "Aurobindo Pharma": "AUROPHARMA.NS",
    "Federal Bank": "FEDERALBNK.NS",
    "Polycab India": "POLYCAB.NS",
    "Indian Hotels": "INDHOTEL.NS",
    "Marico": "MARICO.NS",
    "Colgate Palmoliv": "COLPAL.NS",
    "Pidilite Inds.": "PIDILITIND.NS",
    "Bharat Forge": "BHARATFORG.NS",
    "Container Corp": "CONCOR.NS",
    "Petronet LNG": "PETRONET.NS",
    "Escorts Kubota": "ESCORTS.NS",
    "Balkrishna Inds.": "BALKRISIND.NS",
    "Glenmark Pharma": "GLENMARK.NS",
    "Page Industries": "PAGEIND.NS",
    "Astral": "ASTRAL.NS",
    "Supreme Inds.": "SUPREMEIND.NS",
    "Concord Biotech": "CONCORDBIO.NS",
    "Syngene Intl": "SYNGENE.NS",
    "IPCA Labs": "IPCALAB.NS",
    "Alkem Lab": "ALKEM.NS",
    "Laurus Labs": "LAURUSLABS.NS",
    "Granules India": "GRANULES.NS",
    "JB Chemicals": "JBCHEPHARM.NS",
    "Natco Pharma": "NATCOPHARM.NS",
    "Ajanta Pharma": "AJANTPHARM.NS",
    "Torrent Pharma": "TORNTPHARM.NS",
    "Abbott India": "ABBOTINDIA.NS",
    "Piramal Ent.": "PEL.NS",
    "Gland Pharma": "GLAND.NS",
    "Suzlon Energy": "SUZLON.NS",
    "Mazagon Dock": "MAZDOCK.NS",
    "Cochin Shipyard": "COCHINSHIP.NS",
    "Garden Reach": "GRSE.NS",
    "RVNL": "RVNL.NS",
    "Ircon Intl.": "IRCON.NS",
    "BHEL": "BHEL.NS",
    "NHPC": "NHPC.NS",
    "SJVN": "SJVN.NS",
    "IRFC": "IRFC.NS",
    "REC Ltd": "RECLTD.NS",
    "PFC": "PFC.NS",
    "HUDCO": "HUDCO.NS",
    "IREDA": "IREDA.NS",
    "LIC of India": "LICI.NS",
    "HDFC Life": "HDFCLIFE.NS",
    "SBI Life Insura": "SBILIFE.NS",
    "ICICI Lombard": "ICICIGI.NS",
    "ICICI Pru Life": "ICICIPRULI.NS",
    "Star Health": "STARHEALTH.NS",
    "General Insuranc": "GICRE.NS",
    "New India Assura": "NIACL.NS",
    "Muthoot Finance": "MUTHOOTFIN.NS",
    "M&M Financial": "M&MFIN.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "L&T Finance": "LTF.NS",
    "Manappuram Fin": "MANAPPURAM.NS",
    "IIFL Finance": "IIFL.NS",
    "Poonawalla Fin": "POONAWALLA.NS",
    "CreditAccess": "CREDITACC.NS",
    "Equitas Small": "EQUITASBNK.NS",
    "Ujjivan Small": "UJJIVANSFB.NS",
    "AU Small Finance": "AUBANK.NS",
    "City Union Bank": "CUB.NS",
    "Karur Vysya": "KARURVYSYA.NS",
    "South Ind.Bank": "SOUTHBANK.NS",
    "JK Lakshmi Cem.": "JKLAKSHMI.NS",
    "JK Cement": "JKCEMENT.NS",
    "The Ramco Cement": "RAMCOCEM.NS",
    "Dalmia Bharat": "DALBHARAT.NS",
    "Birla Corp": "BIRLACORPN.NS",
    "India Cements": "INDIACEM.NS",
    "Orient Cement": "ORIENTCEM.NS",
    "Star Cement": "STARCEMENT.NS",
    "Heidelberg Cem.": "HEIDELBERG.NS",
    "Sagar Cements": "SAGCEM.NS",
    "Kesoram Inds.": "KESORAMIND.NS",
    "Prism Johnson": "PRSMJOHNSN.NS",
}

_symbol_cache = {}

def resolve_nse_symbol(mf_name: str) -> str or None:
    if mf_name in _symbol_cache:
        return _symbol_cache[mf_name]
    
    # 1. Exact match
    if mf_name in COMMON_MF_NAME_TO_NSE:
        _symbol_cache[mf_name] = COMMON_MF_NAME_TO_NSE[mf_name]
        return _symbol_cache[mf_name]
        
    # 2. Case-insensitive match
    mf_name_lower = mf_name.lower()
    for k, v in COMMON_MF_NAME_TO_NSE.items():
        if k.lower() == mf_name_lower:
            _symbol_cache[mf_name] = v
            return v
            
    # 3. Fuzzy match using rapidfuzz
    choices = list(COMMON_MF_NAME_TO_NSE.keys())
    match = process.extractOne(mf_name, choices, scorer=fuzz.WRatio)
    
    if match and match[1] >= 88:
        symbol = COMMON_MF_NAME_TO_NSE[match[0]]
        _symbol_cache[mf_name] = symbol
        return symbol
        
    _symbol_cache[mf_name] = None
    return None
